library(ISwR)
attach(thuesen)
names(thuesen)
lm(short.velocity ~ blood.glucose)
summary(lm(short.velocity ~ blood.glucose))
plot(blood.glucose, short.velocity)
abline(lm(short.velocity ~ blood.glucose))

options(na.action = na.exclude)
lm.velo <- lm(short.velocity ~ blood.glucose)
fitted(lm.velo)
resid(lm.velo)
lines(blood.glucose, fitted(lm.velo))
segments(blood.glucose, fitted(lm.velo), blood.glucose, short.velocity)
abline(lm(short.velocity ~ blood.glucose))